//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by factorymanagermfc.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_FACTORY_MANAGER_MFC_DIALOG  102
#define IDR_MAINFRAME                   128
#define IDD_HOME_DIALOG                 132
#define IDB_BACKGROUND                  134
#define IDD_PLACE_DIALOG                135
#define IDD_SEARCH_DIALOG               137
#define IDD_SETTING_DIALOG              139
#define IDD_PLACE_POPUP_DIALOG          141
#define IDD_DIALOG_DETAIL               143
#define IDD_DIALOG_LOGIN                145
#define IDC_TAB1                        1000
#define IDC_EDIT_NAME                   1001
#define IDC_STATIC_NAME                 1002
#define IDC_STATIC_MODEL                1003
#define IDC_EDIT_MODEL                  1004
#define IDC_STATIC_OWNER                1005
#define IDC_EDIT_OWNER                  1006
#define IDC_STATIC_PRICE                1007
#define IDC_EDIT_PRICE                  1008
#define IDC_STATIC_PAY_STATE            1009
#define IDC_RADIO_YES                   1010
#define IDC_RADIO_NO                    1011
#define IDC_BUTTON_INSERT               1012
#define IDC_BUTTON_PLACE                1013
#define IDC_BUTTON__MODIFY              1014
#define IDC_BUTTON__DELETE              1015
#define IDC_BUTTON__EXCEL               1016
#define IDC_INPUT_GRID                  1017
#define IDC_STATIC_AMOUNT               1018
#define IDC_EDIT_AMOUNT                 1019
#define IDC_STATIC_DATE                 1020
#define IDC_DATETIMEPICKER              1021
#define IDC_PLACE_GRID                  1022
#define IDC_BUTTON__EXCEL2              1022
#define IDC_BUTTON__EXCEL_EXPORT        1022
#define IDC_BACK_GRID                   1023
#define IDC_EXHAUST_GRID                1024
#define IDC_STATIC_BACK                 1025
#define IDC_STATIC_EXHAUST              1026
#define IDC_STATIC_PLACE                1027
#define IDC_STATIC_SIMPLE_SEARCH        1028
#define IDC_EDIT_NO                     1029
#define IDC_STATIC_NO                   1030
#define IDC_BUTTON_SIMPLE_SEARCH        1031
#define IDC_STATIC_MODIFY_MOVE_DELETE   1032
#define IDC_STATIC_MODIFY_MOVE_PLACE_NAME 1033
#define IDC_EDIT2                       1034
#define IDC_STATIC_MODIFY_MOVE_DATE     1035
#define IDC_DATETIMEPICKER1             1036
#define IDC_STATIC_MODIFY_MOVE_AMOUNT   1037
#define IDC_DATETIMEPICKER_TO           1037
#define IDC_EDIT_MODIFY_MOVE_AMOUNT     1038
#define IDC_STATIC_BEIZHU               1039
#define IDC_EDIT_BEIZHU                 1040
#define IDC_BUTTON_MODIFY               1041
#define IDC_BUTTON_MOVE                 1042
#define IDC_BUTTON_DELETE               1043
#define IDC_STATIC_BACK_GROUP           1044
#define IDC_STATIC_EXHAUST_GROUP        1045
#define IDC_STATIC_BACK_AMOUNT          1046
#define IDC_EDIT_BACK_AMOUNT            1047
#define IDC_STATIC_BACK_DATE            1048
#define IDC_DATETIMEPICKER_BACK         1049
#define IDC_BUTTON_BACK                 1050
#define IDC_BUTTON_BACK_CANCEL          1051
#define IDC_STATIC_EXHAUST_AMOUNT       1052
#define IDC_STATIC_SEARCH_GROUP         1052
#define IDC_EDIT_EXHAUST_AMOUNT         1053
#define IDC_STATIC_SEARCH_SCOPE         1053
#define IDC_STATIC_EXHAUST_DATE         1054
#define IDC_COMBO_SEARCH_SCOPE          1054
#define IDC_DATETIMEPICKER_EXHAUST      1055
#define IDC_STATIC_PRODUCT_NAME         1055
#define IDC_BUTTON_EXHAUST              1056
#define IDC_EDIT_PRODUCT_NAME           1056
#define IDC_BUTTON_EXHAUST_CANCEL       1057
#define IDC_STATIC_DATE_SCOPE           1057
#define IDC_DATETIMEPICKER_FROM         1058
#define IDC_EDIT_PLACE                  1059
#define IDC_BUTTON_SEARCH               1060
#define IDC_INPUT_SEARCH_GRID           1061
#define IDC_STATIC_SEARCH_RESULT        1062
#define IDC_STATIC_GROUP_PASSWORD       1063
#define IDC_EDIT_OLD_PASSWORD           1064
#define IDC_EDIT_NEW_PASSWORD1          1065
#define IDC_EDIT_NEW_PASSWORD2          1066
#define IDC_BUTTON_CHANGE               1067
#define IDC_STATIC_USER_MANAGE          1068
#define IDC_LIST1                       1069
#define IDC_EDIT_USERNAME               1070
#define IDC_BUTTON_ADD                  1071
#define IDC_EDIT_PASSWORD               1072
#define IDC_SEARCH_PLACE_GRID           1075
#define IDC_MOVE_SEARCH_GRID            1076
#define IDC_DELETE_HISTORY_GRID         1079
#define IDC_EDIT_REMAIN_COUNT           1080
#define IDC_EDIT_PLACE_COUNT            1081
#define IDC_COMBO_BEIZHU                1082
#define IDC_PLACE_DETAIL_GRID           1083
#define IDC_BACK_DETAIL_GRID            1084
#define IDC_EXHAUST_DETAIL_GRID         1085
#define IDC_EDIT1                       1085
#define IDC_BUTTON_BROWSE               1086
#define IDC_EDIT_EXHAUST_BEIZHU         1086
#define IDC_EDIT_FIELD                  1087
#define IDC_BUTTON_VIEW                 1088
#define IDC_STATIC_INPUT                1089
#define IDC_STATIC_FIELD                1090
#define IDC_BUTTON_EXPORT               1092
#define IDC_STATIC_TIRE                 1093
#define IDC_CLOSE                       1095
#define IDC_STATIC_BACK_BEIZHU          1097
#define IDC_STATIC_EXHAUST_BEIZHU       1098
#define IDC_EDIT_BACK_BEIZHU            1099
#define IDC_CHECK1                      1100
#define IDC_CHECK_DATE                  1100

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        149
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1101
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
